[REVIEW][FEATURE][UWANG-60] - membuat component our values
Blue-Habit/bluhabit-landing pull request #16
Opened 2023-12-22 14:48 UTC by fahmi-azzuhri

[REVIEW][FEATURE][UWANG-60] - membuat component our values

#### Description

> add component Our Values

#### Ticket Reference(s)

[UWANG-60](https://bluehabit.atlassian.net/browse/UWANG-60)

#### Validation

##### UI Changes

> Screenshot or video of UI-related changes

##### Coverage

> Test coverage screenshot.

N/A

#### Note(s)

> Mention other user or extra note unrelated to the MR here.

2023-12-23 14:07 UTC, triandamai requested changes

2023-12-23 14:07 UTC, triandamai commented on components/OurValues.vue
> +export default {
Pake composition api aja @fahmi-azzuhri

2023-12-23 14:29 UTC, fahmi-azzuhri commented on components/OurValues.vue
> +export default {
ngehit api nya darimana bang?

2023-12-24 12:35 UTC, triandamai commented on components/OurValues.vue
> +export default {
pake ini mi 
```vue
<script setup lang="ts">

</script>
```

2024-01-03 04:15 UTC, triandamai approved these changes

2024-01-03 04:16 UTC, merged